language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t tommygdev/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true tommygdev/docker-react yarn test

deploy:
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker"
    env: "Docker-env"
    bucket-name: "elasticbeanstalk-us-east-1-605065733753"
    bucket-path: "docker"
    on:
        branch: main
       